name: Civilization
main: com.SamB440.Civilization.Civilization
author: SamB440
website: http://www.islandearth.net
version: 1.0.0
softdepend: [WorldGuard, WorldEdit]
commands:
  Civilization:
     description: Main plugin command.
     usage: /Civilization
     aliases: [Civ]
  Settlement:
     description: Settlement commands.
     usage: /Settlement
     aliases: [sm]